###`Q-1:` Write a program to create an empty series.

In [ ]:
# code here
import pandas as pd
a = pd.Series()
type(a)

pandas.core.series.Series

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [ ]:
a = pd.Series([1,2,3,4,5])
b = pd.Series([6,7,8,9,10])
print(a+b)
print(a*b)
print(a/b)
print(b-a)

0     7
1     9
2    11
3    13
4    15
dtype: int64
0     6
1    14
2    24
3    36
4    50
dtype: int64
0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64
0    5
1    5
2    5
3    5
4    5
dtype: int64

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
# code here
a= pd.Series([2,4,6,8,10]) == pd.Series([1,3,5,7,10])
print(a)

0    False
1    False
2    False
3    False
4     True
dtype: bool

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [ ]:
series = pd.Series([1,2,'Python', 2.0, True, 100])
series = pd.to_numeric(series, errors='coerce')
print(series)

0      1.0
1      2.0
2      NaN
3      2.0
4      1.0
5    100.0
dtype: float64

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

In [ ]:
# code here

df = pd.read_csv('/content/batsman_runs_series.csv')
df.sort_values(by='batsman_run',ascending=False).head(10)

             batter  batsman_run
569         V Kohli         6634
462        S Dhawan         6244
130       DA Warner         5883
430       RG Sharma         5881
493        SK Raina         5536
27   AB de Villiers         5181
108        CH Gayle         4997
339        MS Dhoni         4978
452      RV Uthappa         4954
256      KD Karthik         4377

###`Q-7` No of players having runs above 3000

In [ ]:
# code here
(df['batsman_run']>3000).sum()

20

###`Q-8` No of players having runs above mean value?

In [ ]:
# code here
df[df['batsman_run']>df['batsman_run'].mean()].shape[0]

128

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [ ]:

import pandas as pd
df1=pd.read_csv('/content/items.csv', index_col='item_name')

item_price    50
dtype: int64

In [ ]:
df1['item_price'].isnull().sum()

50

In [ ]:
df1['item_price'] = df1['item_price'].str.replace('$', '').astype(float)
#or
df1['item_price'] = df1['item_price'].apply(lambda x: float(x.replace('$', '')))

In [ ]:
df1.fillna(df1['item_price'].mean(), inplace=True)
df1

                                       item_price
item_name
Chips and Fresh Tomato Salsa                 2.39
Izze                                         3.39
Nantucket Nectar                             3.39
Chips and Tomatillo-Green Chili Salsa        2.39
Chicken Bowl                                16.98
...                                           ...
Steak Burrito                               11.75
Steak Burrito                               11.75
Chicken Salad Bowl                          11.25
Chicken Salad Bowl                           8.75
Chicken Salad Bowl                           8.75

[4622 rows x 1 columns]

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [ ]:
# code here